/**
 * @fileoverview gRPC-Web generated client stub for grpc
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.24.2
// source: chat.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.grpc = require('./chat_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.grpc.ChatServerClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.grpc.ChatServerPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpc.Empty,
 *   !proto.grpc.Note>}
 */
const methodDescriptor_ChatServer_ChatStream = new grpc.web.MethodDescriptor(
  '/grpc.ChatServer/ChatStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.grpc.Empty,
  proto.grpc.Note,
  /**
   * @param {!proto.grpc.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpc.Note.deserializeBinary
);


/**
 * @param {!proto.grpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.grpc.Note>}
 *     The XHR Node Readable Stream
 */
proto.grpc.ChatServerClient.prototype.chatStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/grpc.ChatServer/ChatStream',
      request,
      metadata || {},
      methodDescriptor_ChatServer_ChatStream);
};


/**
 * @param {!proto.grpc.Empty} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.grpc.Note>}
 *     The XHR Node Readable Stream
 */
proto.grpc.ChatServerPromiseClient.prototype.chatStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/grpc.ChatServer/ChatStream',
      request,
      metadata || {},
      methodDescriptor_ChatServer_ChatStream);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.grpc.Note,
 *   !proto.grpc.Empty>}
 */
const methodDescriptor_ChatServer_SendNote = new grpc.web.MethodDescriptor(
  '/grpc.ChatServer/SendNote',
  grpc.web.MethodType.UNARY,
  proto.grpc.Note,
  proto.grpc.Empty,
  /**
   * @param {!proto.grpc.Note} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.grpc.Empty.deserializeBinary
);


/**
 * @param {!proto.grpc.Note} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.grpc.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.grpc.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.grpc.ChatServerClient.prototype.sendNote =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/grpc.ChatServer/SendNote',
      request,
      metadata || {},
      methodDescriptor_ChatServer_SendNote,
      callback);
};


/**
 * @param {!proto.grpc.Note} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.grpc.Empty>}
 *     Promise that resolves to the response
 */
proto.grpc.ChatServerPromiseClient.prototype.sendNote =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/grpc.ChatServer/SendNote',
      request,
      metadata || {},
      methodDescriptor_ChatServer_SendNote);
};


module.exports = proto.grpc;

